#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# Provide defaults if variables are not set
: "${DJANGO_HOST:=django}"
: "${DJANGO_PORT:=5000}"

# Wait for Django backend to be ready
wait-for-it "${DJANGO_HOST}:${DJANGO_PORT}" -t 30
>&2 echo "Django is available"

exec "$@"
