# Generated by Django 5.1.9 on 2025-06-02 10:52

import django.db.models.deletion
import recurrence.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence', recurrence.fields.RecurrenceField(blank=True, null=True)),
                ('recurrence_end', models.DateTimeField(blank=True, null=True)),
                ('recurrence_count', models.PositiveIntegerField(blank=True, null=True)),
                ('frequency', models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], max_length=10, null=True)),
                ('interval', models.PositiveIntegerField(default=1)),
                ('weekdays', models.CharField(blank=True, max_length=13, null=True)),
                ('monthly_pattern', models.CharField(blank=True, choices=[('SAME_DAY', 'Same day each month'), ('RELATIVE_DAY', 'Relative day in month')], max_length=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
