# Generated by Django 5.1.9 on 2025-06-02 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_time',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_time',
            new_name='start',
        ),
        migrations.RemoveField(
            model_name='event',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='event',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='event',
            name='monthly_pattern',
        ),
        migrations.RemoveField(
            model_name='event',
            name='recurrence',
        ),
        migrations.RemoveField(
            model_name='event',
            name='recurrence_count',
        ),
        migrations.RemoveField(
            model_name='event',
            name='recurrence_end',
        ),
        migrations.RemoveField(
            model_name='event',
            name='weekdays',
        ),
        migrations.AddField(
            model_name='event',
            name='exceptions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_rule',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
