name: Continuous Deployment

on:
  push:
    branches: ['fake', 'fake-b']  # Trigger on pushes to main or master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check if secrets are set
        id: check-secrets
        run: |
          if [ -z "${{ secrets.EC2_HOST }}" ] || [ -z "${{ secrets.EC2_USERNAME }}" ] || [ -z "${{ secrets.EC2_SSH_KEY }}" ]; then
            echo "::error::One or more secrets are missing. Please check your GitHub secrets."
            exit 1
          else
            echo "All secrets are set."
          fi

      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/.event
            git fetch origin
            git reset --hard origin/main
            docker compose -f docker-compose.production.yml down
            docker compose -f docker-compose.production.yml up -d --build
